import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import BannerEnd from "../components/BannerEnd";
import ExploreNearby from "../components/ExploreNearby";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LiveAnywhere from "../components/LiveAnywhere";
import styles from "../styles/Home.module.css";

export default function Home({ exploreData, liveAnywhereData }) {
  console.log(exploreData);
  return (
    <div className="">
      <Head>
        <title>AirBnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airbnb-favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* Pull some data from a server = API Endpoints */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, location, distance }) => (
              <ExploreNearby
                key={img}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {liveAnywhereData?.map((item) => (
              <LiveAnywhere key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>
        <BannerEnd
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoor"
          description="Whishlists curated by AirBnb"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(
    (response) => response.json()
  );
  const liveAnywhereData = await fetch("https://links.papareact.com/zp1").then(
    (response) => response.json()
  );
  return {
    props: {
      exploreData,
      liveAnywhereData,
    },
  };
}
